### ISSUE TITLE
@conda-forge-admin, please add user @mikelambert

### ISSUE THREAD

**Issue by siboehm** [conda-forge/anthropic-feedstock#1]

**Comment by siboehm** [comment]
Hi @mikelambert, I packaged anthropics Python sdk for conda-forge. If you want I can add you as a maintainer, so you have more control. There'll be an automatic PR here whenever you push a new PyPI release, I'll handle those.

Since it's a Python-only SDK, there not much work to do.

**Comment by mikelambert** [comment]
Ahh thanks for doing this and thinking to share access back with us :) cc @jenan-anthropic as well
